name: Build and Publish to PyPI using Flit

on:
  push:
    paths:
      - 'src/mmpycorex/_version.py'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Install package dependencies
      run: |
        pip install .
    - name: Build and publish
      run: flit publish